spring:
  data:
    mongodb:
      uri: mongodb+srv://sanjeta:aerog%40123@aerog.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
      database: AeroG

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: aerog
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      missing-topics-fatal: false

server:
  port: 8081
